import Navbar from "@/components/Navbar";
import type { Metadata } from "next";
import { Box, Container } from "@mui/material";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <Navbar />
          <Container maxWidth={false} sx={{ px: 2 }}>
            <Box sx={{ width: "100%", maxWidth: 1200, mx: "auto" }}>
              {children}
            </Box>
          </Container>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}

